### ISSUE TITLE
Access Code

### ISSUE THREAD

**Issue by Bleez103** [Abe-Rybeck/Supreme-Grabber#2]
I'm trying to test your bot, but when running the SupremeGrabbber.jar it is asking for an access code.

**Comment by Abe-Rybeck** [comment]
Current Access Code is "Supreme Grabber".  Will be changed in the future once the project is more complete.

**Comment by Abe-Rybeck** [comment]
Both README.md and ReadME.txt have been updated to include Access code info. thank you.
